title: Andrew Dunning
author: Andrew Dunning
email: andrew.dunning@bl.uk
description: > 
  Curator of Medieval Historical Manuscripts, 1100–1500, at the British Library.
url: "http://andrewdunning.ca"
twitter_username: anjdunning
github_username:  adunning

# Build settings
markdown: kramdown
theme: minima

collections:
  posts:
    permalink: /:title