title:            Andrew Dunning
email:            andrew.dunning@utoronto.ca
author:
  name:           Andrew Dunning
  twitter:        anjdunning
  picture:        /images/bio-photo.jpg
  orcid:          0000-0003-0464-5036
lang:             en-CA
description:      "Teacher, writer, and public speaker in Toronto, Canada"
url:              "https://andrewdunning.ca"
twitter_username: anjdunning
github_username:  adunning

# Build settings
markdown:         kramdown
theme:            minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

collections:
  posts:
    permalink:    /:title

minima:
  date_format:    "%-d %B %Y"

twitter:
  username:       anjdunning

social:
  name:           Andrew Dunning
  links:
    - https://orcid.org/0000-0003-0464-5036
    - https://twitter.com/anjdunning
    - https://github.com/adunning
    - https://www.facebook.com/adunning
    - https://keybase.io/adunning

# Default image for cards
defaults:
  - scope:
      path:       ""
    values:
      image:      /images/bio-photo.jpg
