title: Andrew Dunning
email: andrew.dunning@utoronto.ca
author: Andrew Dunning
description: >
  Teacher, writer, and public speaker in Toronto, Ontario, Canada.
url: "https://andrewdunning.ca"
twitter_username: anjdunning
github_username:  adunning
rss: rss

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

collections:
  posts:
    permalink: /:title

minima:
  date_format: "%-d %B %Y"
