title: Andrew Dunning
author: Andrew Dunning
description: > 
  Teacher, writer, and public speaker in Toronto, Ontario, Canada.
url: "https://andrewdunning.ca"
twitter_username: anjdunning
github_username:  adunning

# Build settings
markdown: kramdown
theme: minima
exclude:
  - Gemfile
  - Gemfile.lock

collections:
  posts:
    permalink: /:title